<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
    <Nullable>enable</Nullable>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>17.0.0-alpha001</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo Emply</Title>
    <Description>Umbraco integration for the Emply API.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Limbo.Umbraco.Emply</PackageId>
    <PackageTags>Limbo, Skybrud, Umbraco, Emply, API, JSON, Jobs</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/limbo.umbraco.emply/v17/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/limbo-works/Limbo.Umbraco.Emply</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="Authors" Value="$(Authors)" />
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/limbo.umbraco.emply/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/limbo.umbraco.emply/docs/v17/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Limbo.Umbraco.Emply" />
    <AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/limbo.umbraco.emply" />
  </ItemGroup>

  <!-- Ignore vulnerabilities from transient dependencies -->
  <PropertyGroup>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Limbo.Integrations.Emply" Version="1.0.2" />
    <PackageReference Include="Skybrud.Essentials" Version="1.1.69" />
    <PackageReference Include="Skybrud.Essentials.AspNetCore" Version="1.0.2" />
    <PackageReference Include="Skybrud.Essentials.Http" Version="1.2.3" />
    <PackageReference Include="Skybrud.Essentials.Umbraco" Version="17.0.0-alpha008" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[17.4.2,17.999)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.4.2,17.999)" />
  </ItemGroup>

  <!-- Include package icon for NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <!-- Include custom appsettings schema -->
  <ItemGroup>
    <None Include="appsettings-schema.Limbo.Umbraco.Emply.json" Pack="true" PackagePath="" />
    <None Include="buildTransitive\Limbo.Umbraco.Emply.targets" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>

</Project>